image: "python:3.9-bookworm"

cache:
  paths:
    - .apt
    - deps_cache
    - venv/

.install_dependencies: &install_dependencies
  - rm -f /etc/apt/apt.conf.d/docker-clean
  - mkdir .apt && mount --bind .apt /var/cache/apt/archives/
  - apt-get update
  - apt-get install -y git cmake

.install_openfhe_development: &install_openfhe_development
  - git clone https://github.com/openfheorg/openfhe-development.git
  - cd openfhe-development
  - mkdir build 
  - cd build
  - cmake -DBUILD_UNITTESTS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_BENCHMARKS=OFF ..
  - make -j$(nproc)
  - make install
  - export LD_LIBRARY_PATH=/usr/local/lib:${LD_LIBRARY_PATH}

.install_openfhe_python: &install_openfhe_python
  - git clone https://github.com/openfheorg/openfhe-python.git
  - cd openfhe-python
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - make install

before_script:
  - *install_dependencies
  - *install_openfhe_development
  - python --version
  - python -m venv venv
  - source venv/bin/activate
  - pip install "pybind11[global]" mypy ruff pytest
  - *install_openfhe_python
  - cd ../../../..
  - pip install .

stages:
  - Static Analysis
  - Test

mypy:
  stage: Static Analysis
  only:
    - main
    - merge_requests
  allow_failure: true
  script:
    - mypy .

ruff:
  stage: Static Analysis
  only:
    - main
    - merge_requests
  allow_failure: true
  script:
    - ruff check .

pytest:
  stage: Test
  only:
    - main
    - merge_requests
  allow_failure: true
  script:
   - pytest
